#!/usr/bin/env bash

# get path of this file
home="`dirname $BASH_SOURCE`/../"

# add bear bin path
export PATH="${home}/bin:${PATH}"

# add alias 
for file in `ls ${home}/conf/alias`
do
    source ${home}"/conf/alias/"$file
done


